# For use with: https://docs.platformio.org/en/stable/boards/espressif32/az-delivery-devkit-v4.html
esp32:
  board: az-delivery-devkit-v4
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y

uart:
  id: uart_ecodan
  rx_pin:
    number: GPIO3 #RX pin on pcb
    mode:
      input: true
      pullup: true
  tx_pin:
    number: GPIO1 #TX pin on pcb
    mode:
      output: true
  baud_rate: 2400
  parity: EVEN
  stop_bits: 1
  # debug:
  #   direction: BOTH
  #   dummy_receiver: false
  #   after:
  #     delimiter: "\n"
  #   sequence:
  #     - lambda: UARTDebug::log_hex(direction, bytes, ' ');

sensor:
  - platform: internal_temperature
    name: ${internal_esp_temperature}
    entity_category: diagnostic
