esphome:
  name: ${name}
  friendly_name: ${friendlyName}
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: lolin_s3_mini
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y


uart:
  - id: uart_ecodan
    rx_pin:
      number: GPIO18
      mode:
        input: true
        pullup: true
    tx_pin:
      number: GPIO16
      mode:
        output: true
    baud_rate: 2400
    parity: EVEN
    stop_bits: 1
    # debug:
    #   direction: BOTH
    #   dummy_receiver: false
    #   after:
    #     delimiter: "\n"
    #   sequence:
    #     - lambda: UARTDebug::log_hex(direction, bytes, ' ');

light:
  - platform: esp32_rmt_led_strip
    name: Led
    id: led
    internal: true
    rgb_order: RGB
    pin: GPIO47
    num_leds: 1
    rmt_channel: 0
    chipset: ws2812
    restore_mode: ALWAYS_OFF
    effects:
      - pulse:
          name: slow_pulse
          transition_length: 250ms
          update_interval: 250ms
          min_brightness: 25%
          max_brightness: 100%
      - pulse:
          name: fast_pulse
          transition_length: 100ms
          update_interval: 100ms
          min_brightness: 25%
          max_brightness: 100%

button:
  - platform: restart
    id: restart_button
    name: ${restart_button}

sensor:
  - platform: internal_temperature
    name: ${internal_esp_temperature}
    entity_category: diagnostic
